### ISSUE TITLE
Doesn't work in the browser

### ISSUE THREAD

**Issue by maslick** [joaquimserafim/node-netcat#4]
Is it possible to use it in the browser (using browserify)?
I am getting this error:

```
this._client = net.connect({port: self._port, host: self._host}, connect);
Uncaught TypeError: undefined is not a function
```

**Comment by joaquimserafim** [comment]
Hey, no this module can't be used in the browser :(

cheers

**Comment by joaquimserafim** [comment]
Hey, I'm closing this for now but if you find a solution let me know 

thanks
